import { Injectable } from '@nestjs/common';
import axios from 'axios';

@Injectable()
export class DatafinitiService {
  constructor() {}

  async getPropertyByNormalizedAddress(
    address: string,
    city: string,
    province: string,
    postalCode: string,
  ): Promise<any> {
    const apiKey = process.env.DATAFINITI_API_KEY;
    if (!apiKey) {
      return [];
    }

    const normalizedAddress = normalizeAddress(address);

    const url = 'https://api.datafiniti.co/v4/properties/search';
    const payload = {
      query: `address:"${normalizedAddress}" AND city:${city} AND province:${province} AND postalCode:${postalCode}`,
      num_records: 1,
    };

    try {
      const response = await axios.post(url, payload, {
        headers: {
          'Content-Type': 'application/json',
          Authorization: `Bearer ${apiKey}`,
        },
      });
      return response.data;
    } catch (error) {
      console.error(
        'Datafiniti API error:',
        error.response?.data || error.message,
      );
      throw error;
    }
  }
}

function normalizeAddress(address: string): string {
  // Map of address terms to their normalized forms
  const normalizationMap: Record<string, string> = {
    ALLEY: 'ALY',
    ANNEX: 'ANX',
    ARCADE: 'ARC',
    AVENUE: 'AVE',
    BAYOO: 'BYU',
    BEACH: 'BCH',
    BEND: 'BND',
    BLUFF: 'BLF',
    BLUFFS: 'LFS',
    BOTTOM: 'BTM',
    BOULEVARD: 'BLVD',
    BRANCH: 'BR',
    BRIDGE: 'BRG',
    BROOK: 'BRK',
    BROOKS: 'BRKS',
    BURG: 'BG',
    BURGS: 'BGS',
    BYPASS: 'BYP',
    CAMP: 'CP',
    CANYON: 'CYN',
    CAPE: 'CPE',
    CAUSEWAY: 'CSWY',
    CENTER: 'CTR',
    CENTERS: 'CTRS',
    CIRCLE: 'CIR',
    CIRCLES: 'CIRS',
    CLIFF: 'CLF',
    CLIFFS: 'CLFS',
    CLUB: 'CLB',
    COMMON: 'CMN',
    CORNER: 'COR',
    CORNERS: 'CORS',
    COURSE: 'CRSE',
    COURT: 'CT',
    COURTS: 'CTS',
    COVE: 'CV',
    COVES: 'CVS',
    CREEK: 'CRK',
    CRESCENT: 'CRES',
    CREST: 'CRST',
    CROSSING: 'XING',
    CROSSROAD: 'XRD',
    CURVE: 'CURV',
    DALE: 'DL',
    DAM: 'DM',
    DIVIDE: 'DV',
    DRIVE: 'DR',
    DRIVES: 'DRS',
    ESTATE: 'EST',
    ESTATES: 'ESTS',
    EXPRESSWAY: 'EXPY',
    EXTENSION: 'EXT',
    EXTENSIONS: 'EXTS',
    FALL: 'FALL',
    FALLS: 'FLS',
    FERRY: 'FRY',
    FIELD: 'FLD',
    FIELDS: 'FLDS',
    FLAT: 'FLT',
    FLATS: 'FLTS',
    FORD: 'FRD',
    FORDS: 'FRDS',
    FOREST: 'FRST',
    FORGE: 'FRG',
    FORGES: 'FRGS',
    FORK: 'FRK',
    FORKS: 'FRKS',
    FORT: 'FT',
    FREEWAY: 'FWY',
    GARDEN: 'GDN',
    GARDENS: 'GDNS',
    GATEWAY: 'GTWY',
    GLEN: 'GLN',
    GLENS: 'GLNS',
    GREEN: 'GRN',
    GREENS: 'GRNS',
    GROVE: 'GRV',
    GROVES: 'GRVS',
    HARBOR: 'HBR',
    HARBORS: 'HBRS',
    HAVEN: 'HVN',
    HEIGHTS: 'HTS',
    HIGHWAY: 'HWY',
    HILL: 'HL',
    HILLS: 'HLS',
    HOLLOW: 'HOLW',
    INLET: 'INLT',
    INTERSTATE: 'I',
    ISLAND: 'IS',
    ISLANDS: 'ISS',
    ISLE: 'ISLE',
    JUNCTION: 'JCT',
    JUNCTIONS: 'JCTS',
    KEY: 'KY',
    KEYS: 'KYS',
    KNOLL: 'KNL',
    KNOLLS: 'KNLS',
    LAKE: 'LK',
    LAKES: 'LKS',
    LAND: 'LAND',
    LANDING: 'LNDG',
    LANE: 'LN',
    LIGHT: 'LGT',
    LIGHTS: 'LGTS',
    LOAF: 'LF',
    LOCK: 'LCK',
    LOCKS: 'LCKS',
    LODGE: 'LDG',
    LOOP: 'LOOP',
    MALL: 'MALL',
    MANOR: 'MNR',
    MANORS: 'MNRS',
    MEADOW: 'MDW',
    MEADOWS: 'MDWS',
    MEWS: 'MEWS',
    MILL: 'ML',
    MILLS: 'MLS',
    MISSION: 'MSN',
    MOORHEAD: 'MHD',
    MOTORWAY: 'MTWY',
    MOUNT: 'MT',
    MOUNTAIN: 'MTN',
    MOUNTAINS: 'MTNS',
    NECK: 'NCK',
    ORCHARD: 'ORCH',
    OVAL: 'OVAL',
    OVERPASS: 'OPAS',
    PARK: 'PARK',
    PARKS: 'PARK',
    PARKWAY: 'PKWY',
    PARKWAYS: 'PKWY',
    PASS: 'PASS',
    PASSAGE: 'PSGE',
    PATH: 'PATH',
    PIKE: 'PIKE',
    PINE: 'PNE',
    PINES: 'PNES',
    PLACE: 'PL',
    PLAIN: 'PLN',
    PLAINS: 'PLNS',
    PLAZA: 'PLZ',
    POINT: 'PT',
    POINTS: 'PTS',
    PORT: 'PRT',
    PORTS: 'PRTS',
    PRAIRIE: 'PR',
    RADIAL: 'RADL',
    RAMP: 'RAMP',
    RANCH: 'RNCH',
    RAPID: 'RPD',
    RAPIDS: 'RPDS',
    REST: 'RST',
    RIDGE: 'RDG',
    RIDGES: 'RDGS',
    RIVER: 'RIV',
    ROAD: 'RD',
    ROADS: 'RDS',
    ROUTE: 'RTE',
    ROW: 'ROW',
    RUE: 'RUE',
    RUN: 'RUN',
    SHOAL: 'SHL',
    SHOALS: 'SHLS',
    SHORE: 'SHR',
    SHORES: 'SHRS',
    SKYWAY: 'SKWY',
    SPRING: 'SPG',
    SPRINGS: 'SPGS',
    SPUR: 'SPUR',
    SPURS: 'SPUR',
    SQUARE: 'SQ',
    SQUARES: 'SQS',
    STATION: 'STA',
    STREAM: 'STRM',
    STREET: 'ST',
    STREETS: 'STS',
    SUMMIT: 'SMT',
    THROUGHWAY: 'TRWY',
    TRACE: 'TRCE',
    TRACK: 'TRAK',
    TRAIL: 'TRL',
    TUNNEL: 'TUNL',
    TURNPIKE: 'TPKE',
    UNDERPASS: 'UPAS',
    UNION: 'UN',
    UNIONS: 'UNS',
    VALLEY: 'VLY',
    VALLEYS: 'VLYS',
    VIADUCT: 'VIA',
    VIEW: 'VW',
    VIEWS: 'VWS',
    VILLAGE: 'VLG',
    VILLAGES: 'VLGS',
    VILLE: 'VL',
    VISTA: 'VIS',
    WALK: 'WALK',
    WALKS: 'WALK',
    WALL: 'WALL',
    WAY: 'WAY',
    WAYS: 'WAYS',
    WELL: 'WL',
    WELLS: 'WLS',
    APARTMENT: 'APT',
    BASEMENT: 'BSMT',
    BUILDING: 'BLDG',
    DEPARTMENT: 'DEPT',
    FLOOR: 'FL',
    FRONT: 'FRNT',
    HANGAR: 'HNGR',
    LOBBY: 'LBBY',
    LOT: 'LOT',
    LOWER: 'LOWR',
    OFFICE: 'OFC',
    PENTHOUSE: 'PH',
    PIER: 'PIER',
    REAR: 'REAR',
    ROOM: 'RM',
    SIDE: 'SIDE',
    SLIP: 'SLIP',
    SPACE: 'SPC',
    STOP: 'STOP',
    SUITE: 'STE',
    TRAILER: 'TRLR',
    UNIT: 'UNIT',
    UPPER: 'UPPR',
  };

  // Replace each full word in the address using the normalization map
  // \b for word boundaries, global & case-insensitive
  let normalized = address.toUpperCase();

  for (const [key, value] of Object.entries(normalizationMap)) {
    const regex = new RegExp(`\\b${key}\\b`, 'g');
    normalized = normalized.replace(regex, value);
  }

  // Remove punctuation: periods and commas (as before)
  normalized = normalized.replace(/[.,]/g, '');

  // Trim whitespace
  normalized = normalized.trim();

  return normalized;
}
